---
title: "Bootstrap"
author: "Prabidhik KC"
date: "2022-11-24"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## In this module I will be doing bootstrap

```{r}
library(tidyverse)
library(gov50data)
library(infer)
```

```{r}
anes
```
```{r}
anes %>% 
  summarize(sci_mean = mean(sci_therm))
```

```{r}
## bootstrap: sampling from the population by resampling many times the sample itself
## boostrap: sampling from the population by resampling the sample itself many times

boot_1 <- anes %>% 
  slice_sample(prop = 1, replace = TRUE)

boot_1 %>% 
  summarize(sci_mean1 = mean(sci_therm))


```
```{r}
bootstrap_dist <- anes %>% 
  rep_slice_sample(prop = 1, replace = TRUE, reps = 1000) %>% 
  group_by(replicate)  %>% 
  summarize(mean_sci_therm = mean(sci_therm))

bootstrap_dist 

tail(bootstrap_dist)
```

```{r}
bootstrap_dist %>% 
  ggplot(mapping = aes(x = mean_sci_therm)) +
  geom_histogram(mapping = aes(y = ..density..), binwidth = 0.1)
```

```{r}
perc_ci99 <- quantile(bootstrap_dist$mean_sci_therm,
  probs = c(0.005, 0.995))

perc_ci99
```

```{r}
perc_ci95 <- quantile(bootstrap_dist$mean_sci_therm,
                      probs = c(0.025, 0.975))
perc_ci95
```

```{r}
boot_dist_infer <- anes %>% 
  specify(response = sci_therm) %>% 
  generate(reps = 1000, type = "bootstrap") %>% 
  calculate(stat = "mean") 

boot_dist_infer

perc_ci_95 <- boot_dist_infer %>% 
  get_confidence_interval(level = 0.95, type = "percentile") 
perc_ci_95
  

```
```{r}
visualize(boot_dist_infer) +
  shade_confidence_interval(endpoints = perc_ci_95)
```

